### ISSUE TITLE
Outdated - API Keys

### ISSUE THREAD

**Issue by ptavasci** [GDKsoftware/unleash-client-delphi#1]
Marco, this project seems to be outdated. It was uploaded 2 years ago and API Keys showed up in version 4 of Unleash, which was released later on.

Have you been using it? Would you care to share the updates if so?
Thanks in advance!

**Comment by partouf** [comment]
Hi, yes we've been using it for a couple of Delphi applications in combination with a self-hosted server, this server doesn't require authorization for the public part of the API.

I have some time in 1 or 2 weeks to look at the changes and see what we have to change for newer versions of the server.

Thanks for the feedback!

**Comment by ptavasci** [comment]
Thanks Patrick! Happy Hollidays!!

**Comment by partouf** [comment]
Happy holidays!

I have added and tested the api key, you can set it with `Config.apiKey := 'user.production.12ab34cd56ef57ab89cd';` - using the token you can generate by following this guide https://docs.getunleash.io/user_guide/api-token

Let me know if you have any issues

**Comment by ptavasci** [comment]
Worked like a charm.
Thanks!!!
